spring.application.name=platzi-pizzeria

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//172.22.3.116:11213/EJCGETDE
spring.datasource.username=TIENDA
spring.datasource.password=oracle

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none